### ISSUE TITLE
conf folder empty

### ISSUE THREAD

**Issue by openstampede** [koillection/koillection#1117]
Hello. I've noticed my Koillection instance needs to go through (at least some of) the first startup process every time the container is rebooted (running in Docker on a Synology NAS). One item needs to be responded to manually each time:

"You are about to replace your existing keys. Are you sure you wish to continue? (yes/no)"

I assume this is because the /conf folder never seems to be used. It is always empty. Any advice would be appreciated.

Edit to clarify:

I have /conf mapped to a folder on the host. However, both the folder on the container and the mapped folder are always empty. The mapped folder for /uploads seems to work fine.

**Comment by benjaminjonard** [comment]
Hello, which version of Koillection  do you have installed ? I removed the /conf folder a while ago, I just want to make sure this problem isn't occurring because of an old version.

Either way, could you copy and paste the few previous lines from the logs just before the question you see ? 

Edit: I'll update the docker entrypoint for the next release, it should stop asking that question

**Comment by openstampede** [comment]
You may no longer need it, since it seems like you found why it's happening, but these are the lines before and after the question (there's also a PHP warning at the end, but I don't know if that matters). Please forgive the screenshot. The log export from the Synology NAS is formatted even worse than this is.

![image](https://github.com/benjaminjonard/koillection/assets/81187861/bd5aa812-0f46-4ae1-a1a9-50ef1e081cf0)
