### ISSUE TITLE
Scraper can't fill template fields

### ISSUE THREAD

**Issue by tedr56** [koillection/koillection#895]
Thanks for the first scrapper implementation. It looks promising.

I was playing with and mostly trying to get the hand of xpath.
I think I'm getting there. But I noticed somethings.

I couldn't fill a numeric field from a template with the value a scrapper field.
I was wondering if it was a type error, since scrapper gets text value.
So I change the type inside my template, and no success.

The scrapper field has to be "non existant" so the scrapper can add it.

I don't know if it's by design or a bug.

Can you share some light on this?

Thanks.

**Comment by tedr56** [comment]
I can add that even fields created by scrapper can't be filled in case of second scrap.

**Comment by benjaminjonard** [comment]
Hello, 

It's by design, but an old design :sweat_smile:  Scrapers rely on the same code as any other things (like templates) that interact with fields. It's a pretty old code now, and it can certainly be improved.

~~I'm going to update it so that at least text and number fields will be filled if they already exists.~~ Edit: it should be working with every type of fields

**Comment by benjaminjonard** [comment]
It should work new with the new release (1.4.10)
