### ISSUE TITLE
Search in data doesn't work for lists

### ISSUE THREAD

**Issue by michalterbert** [koillection/koillection#907]
Hi Team,
Im using koillection (docer, v1.4.10).

Today I just found small bug - I have collection of vinyls + scrapper discogs, after all I have for each item nice looking list of songs, but search cant work with them.

List element value is not searchable (after checked option "search in data (for items and collection)"

BTW. Great product :)

**Comment by benjaminjonard** [comment]
Hello, thank you very much :) The 'search in data' option only searched in text fields because at the time of its development, text fields were the only relevant type of field for searching. 

I've enabled the search for textareas, lists, and choice lists. This feature will be available in the next release.

**Comment by michalterbert** [comment]
@benjaminjonard thanks for quick response and add this to next feature :)

I have one more question, could you add simple sorting arrows (and sorting possibility) to table header?
![obraz](https://github.com/benjaminjonard/koillection/assets/15417117/75c110d9-3912-48d5-b189-8965da06a7f8)

**Comment by benjaminjonard** [comment]
I've added that too, it still needs more tests but it should be available soon
